#! /bin/bash

LISTEN_PORT=${LISTEN_PORT:-443}
LISTEN_ADDR=${LISTEN_ADDR:-0.0.0.0:$LISTEN_PORT}

HOST_ADDR=$(ip route|awk '/default/ { print $3 }')

SSH_TARGET_PORT=${SSL_TARGET_PORT:-22}
SSL_TARGET_PORT=${SSL_TARGET_PORT:-443}

SSH_TARGET_ADDR=${SSH_TARGET_ADDR:-$HOST_ADDR:$SSH_TARGET_PORT}
SSL_TARGET_ADDR=${SSL_TARGET_ADDR:-$HOST_ADDR:$SSL_TARGET_PORT}

echo in: $LISTEN_ADDR
echo ssl: $SSL_TARGET_ADDR
echo ssh: $SSH_TARGET_ADDR
sslh -p $LISTEN_ADDR --ssl $SSL_TARGET_ADDR --ssh $SSH_TARGET_ADDR -f
