#! /bin/bash

# make target directories
mkdir -p /mnt/amazon
mkdir -p /mnt/decrypted
mkdir -p /input/.cache/acd_cli
rm -r /root/.cache
ln -s /input/.cache /root/.cache

# mount amazon cloud drive
cp /input/oauth_data /root/.cache/acd_cli/oauth_data

/root/mount.sh

# show what our local ip is so other services can rsync here
ip -o addr show eth0 | awk /'inet/ {print $2 "\t" $3 "\t" $4}'

# rsyncd
cp /input/rsyncd.secrets /root/rsyncd.secrets && chmod a-r /root/rsyncd.secrets
/usr/bin/rsync --no-detach --daemon --config="/root/rsyncd.conf" &
echo "startup complete"
