#! /bin/bash

# make target directories
mkdir -p /mnt/acd-raw
mkdir -p /input/.cache/acd_cli
mkdir -p /input/.cache/borg
rm -r /root/.cache
ln -s /input/.cache /root/.cache

# mount amazon cloud drive
cp /input/oauth_data /root/.cache/acd_cli/oauth_data
acdcli sync
acdcli mount /mnt/acd-raw

# borg backup
export BORG_PASSPHRASE=`cat /input/borgbackup.secrets`
export BORG_REPO=/mnt/acd-raw

# run CMD
exec "$@"
