#! /bin/bash

# copy in config
cp /input/oauth_data /root/.cache/acd_cli/oauth_data
#cp /input/.ecryptfsrc /root/.ecryptfsrc
cp /input/gocryptfs.secrets /root/gocryptfs.secrets
cp /input/rsyncd.secrets /root/rsyncd.secrets && chmod a-r /root/rsyncd.secrets

# make target directories
mkdir -p /mnt/acd-raw
mkdir -p /mnt/acd-decrypted

# mount amazon cloud drive
acd_cli sync
acd_cli --no-log mount /mnt/acd-raw

# mount encrypted filesystem over it
#mount -t ecryptfs -o no_sig_cache /mnt/acd-raw /mnt/acd-decrypted
cat /root/gocryptfs.secrets | gocryptfs -nosyslog /mnt/acd-raw /mnt/acd-decrypted/

# show what our local ip is so other services can rsync here
ip -o addr show eth0 | awk /'inet/ {print $2 "\t" $3 "\t" $4}'

# rsyncd time
/usr/bin/rsync --no-detach --daemon --config="/root/rsyncd.conf" &
echo "startup complete"
