#! /bin/bash

# add a user to run commands with
if [ -f /root/.docker-runrc ]; then
  #uid:username:groups:password
  USER_NAME=`cut -d : -f 2   /root/.docker-runrc`
  USER_PASS=`cut -d : -f 4-  /root/.docker-runrc`
  USER_GROUPS=`cut -d : -f 3 /root/.docker-runrc`
  USER_ID=`cut -d : -f 1     /root/.docker-runrc`
else
  USER_NAME=${USER_NAME:=docker}
  USER_PASS=${USER_PASS:=docker}
  USER_GROUPS=${USER_GROUPS:=audio,sudo}
  USER_ID=${USER_ID:=1000}
fi

# create that user
useradd -m $USER_NAME -u $USER_ID -G $USER_GROUPS > /dev/null 2>&1
chpasswd <<< "$USER_NAME:$USER_PASS"
chown $USER_NAME /home/$USER_NAME
touch /home/$USER_NAME/.Xauthority; chown $USER_NAME /home/$USER_NAME/.Xauthority # gksu needs this file, even if empty
chsh -s /bin/bash $USER_NAME
cd /home/$USER_NAME

# run command as user
if [ $# -eq 0 ]; then
  USER=$USER_NAME LOGNAME=$USER_NAME exec gosu $USER_NAME bash
else
  USER=$USER_NAME LOGNAME=$USER_NAME exec gosu $USER_NAME "$@"
fi
